### ISSUE TITLE
Al acceder hacer click en el icono del sitio debería llevarme a la home page

### ISSUE THREAD

**Issue by geronm12** [FNicastroTorresDev/sushi-n-code-front#20]
SITUACTION ACTUAL
Acceder al sitio web sin iniciar sesión, hacer click en pedir ya o ir a login, intentar volver haciendo click en el logo de la empresa.

RESULTADO 
El logo nos lleva siempre al login y se despliega un mensaje de error en consola

RESULTADO ESPERADO
El logo nos debería llevar nuevamente a la home page

Adjunto Pruebas
![image](https://github.com/FNicastroTorresDev/sushi-n-code-front/assets/44532299/7f7d7f3d-ae3b-44ab-98de-acf10dea6e80)

https://github.com/FNicastroTorresDev/sushi-n-code-front/assets/44532299/e1421488-8098-418b-b462-bdbe3fe7a38b

**Comment by FNicastroTorresDev** [comment]
Solucionado con correcciones en rutas protegidas.

Evidencia:

https://github.com/FNicastroTorresDev/sushi-n-code-front/assets/115121008/c2915fc2-9be8-4b52-a1d6-208fedfd2fbd
