### ISSUE TITLE
Al intentar iniciar sesion y colocar mal la contraseña el spinner no desaparece

### ISSUE THREAD

**Issue by geronm12** [FNicastroTorresDev/sushi-n-code-front#21]
SITUACION ACTUAL
Dirigirse a la url para iniciar sesión, colocar las credenciales del usuario correctas pero la contraseña incorrecta.

RESULTADO OBTENIDO
El mensaje de error aparece correctamente pero el spinner nunca desaparece

RESULTADO ESPERADO
El spinner debería desaparecer y permitir al usuario ingresar nuevamente los datos correctos

Adjunto Pruebas

![image](https://github.com/FNicastroTorresDev/sushi-n-code-front/assets/44532299/d9251255-3352-4163-b65e-a71bdc1d8144)

https://github.com/FNicastroTorresDev/sushi-n-code-front/assets/44532299/e74e88c9-91f0-484a-9f44-1071ced00430

**Comment by Daniel-Teseira** [comment]
Solucion: se agrego un cambio de estado al spinner

Evidencia

https://github.com/FNicastroTorresDev/sushi-n-code-front/assets/74610396/03517d54-eb3f-417a-9436-bd61d1f7860c
