### ISSUE TITLE
Eliminar un menu con un pedido en curso

### ISSUE THREAD

**Issue by geronm12** [FNicastroTorresDev/sushi-n-code-front#22]
SITUACION ACTUAL
Iniciar sesión como usuario administrador, seleccionar un menu que posea un pedido en curso y eliminarlo

RESULTADO OBTENIDO
El menu se elimina

RESULTADO ESPERADO
Si el menú que intento borrar posee algún pedido pendiente, el sistema no debería permitirme eliminar dicho menú hasta no tener todos los menúes confirmados.

Adjunto Pruebas

https://github.com/FNicastroTorresDev/sushi-n-code-front/assets/44532299/01765d88-e472-4163-9083-6eefe3351c90

**Comment by Daniel-Teseira** [comment]
Solucion: se agrego comprovacion para el borrado de un menu verificando si hay pedidos pendientes del mismo

Evidencia:

https://github.com/FNicastroTorresDev/sushi-n-code-front/assets/74610396/7a671697-bcb2-4a85-a01c-4f37b659d850
