### ISSUE TITLE
Un usuario no debería poder inhabilitarse a si mismo

### ISSUE THREAD

**Issue by geronm12** [FNicastroTorresDev/sushi-n-code-front#23]
SITUACION ACTUAL
Iniciar sesión como usuario de tipo administradoir, buscar la página de administración y bloquear el usuario con el mail asociado al usuario que usamos a iniciar sesión.

RESULTADO OBTENIDO
El usuario se puede inhablitar a si mismo

RESULTADO ESPERADO
Un usuario no debería poder inhablitarse a si mismo

Adjunto Pruebas

https://github.com/FNicastroTorresDev/sushi-n-code-front/assets/44532299/c1d6ab29-ec8c-4f1b-bc9c-5b7f6b8f5156

**Comment by FNicastroTorresDev** [comment]
Solucionado añadiendo condición en el mapeo del cuadro.

Evidencia:

https://github.com/FNicastroTorresDev/sushi-n-code-front/assets/115121008/9ed2766f-3db8-43ec-9bdc-de10f891070f

Ahora aparece este ícono en lugar del botón de habilitar/inhabilitar con el title "Usuario actual":
![image](https://github.com/FNicastroTorresDev/sushi-n-code-front/assets/115121008/0a6280a9-a2c0-4f9f-a05f-704dbc7e3de4)
